<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WzHack.Loader</RootNamespace>
    <AssemblyName>wzhack</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../warzone-hack.Core/warzone-hack.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
